	CREATE TABLE "MEMBER" 
   (	"SSN" NUMBER NOT NULL ENABLE, 
	"MEM_TYPE_ID" NUMBER, 
	"First_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"Middle_NAME" VARCHAR2(10 BYTE), 
	"Last_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"CAMPUS_ADDRESS" VARCHAR2(1000 BYTE), 
	"MAIL_ADDRESS" VARCHAR2(1000 BYTE), 
	"CARD_NUM" NUMBER, 
	 CONSTRAINT "MEMBER_PK" PRIMARY KEY ("SSN"),
	 CONSTRAINT "MEM_TYPE_FK" FOREIGN KEY ("MEM_TYPE_ID")
	  REFERENCES "MEMBER_TYPE" ("MEM_TYPE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "CD_NUM_FK" FOREIGN KEY ("CARD_NUM")
	  REFERENCES "CARDS" ("CARD_NUM") ON DELETE CASCADE ENABLE
   ) ;
   
    CREATE TABLE "MEMBER_TYPE" 
   (	"MEM_TYPE_ID" NUMBER NOT NULL ENABLE, 
	"MEM_TYPE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"EMP_TYPE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DAYS_DUE" NUMBER, 
	"DAYS_GRACE" NUMBER, 
	 CONSTRAINT "MEMBER_TYPE_PK" PRIMARY KEY ("MEM_TYPE_ID"));
	 
	 
	CREATE TABLE "BOOKS" 
   (	"ISBN" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"BOOK_DESC" VARCHAR2(4000 BYTE), 
	"SUBJ_AREA" VARCHAR2(30 BYTE), 
	"AUTHOR" VARCHAR2(50 BYTE), 
	"BINDING" VARCHAR2(200 BYTE), 
	"EDITION" VARCHAR2(30 BYTE), 
	"LANGUAGE" VARCHAR2(200 BYTE), 
	"BOOK_TYPE" VARCHAR2(20 BYTE), 
	"IS_AVAILABLE" CHAR(1 BYTE) NOT NULL ENABLE, 
	 CHECK (IS_AVAILABLE IN('Y','N')) ENABLE, 
	 CONSTRAINT "TITLE_PK" PRIMARY KEY ("ISBN"));
     
    CREATE TABLE "VOLUMES" 
   (	"BOOK_ID" NUMBER, 
	"ISBN" NUMBER NOT NULL ENABLE, 
	"FLAG" CHAR(1 BYTE) DEFAULT 'N', 
	"Date" DATE, 
	"OLD_BOOK_ID" NUMBER DEFAULT NULL, 
	"STATUS" VARCHAR2(20 BYTE), 
	 CHECK (FLAG IN('Y','N')) ENABLE, 
	 CONSTRAINT "VOLUMES_PK" PRIMARY KEY ("BOOK_ID"),
	 CONSTRAINT "TITLE_FK" FOREIGN KEY ("ISBN")
	  REFERENCES "BOOKS" ("ISBN") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "VOLUMES_OLD_FK" FOREIGN KEY ("OLD_BOOK_ID")
	  REFERENCES "VOLUMES" ("BOOK_ID") ENABLE
   ) ; 

	CREATE TABLE "CARDS" 
   (	"CARD_NUM" NUMBER, 
	"PHOTO" BLOB, 
	"CARD_STATUS" CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE, 
	"ISSUE_DATE" DATE, 
	"EXPIRY_DATE" DATE, 
	 CONSTRAINT "CARDS_PK" PRIMARY KEY ("CARD_NUM"));
	 
	CREATE TABLE "BORROWS" 
   (	"BOOK_ID" NUMBER, 
	"MSSN" NUMBER, 
	"ISSUED_BY" NUMBER, 
	"BORROW_STATUS" VARCHAR2(20 BYTE), 
	"DUE_DATE" DATE, 
	"GRACE_PERIOD" DATE, 
	"ISSUE_DATE" DATE, 
	"RETURN_DATE" DATE, 
	 CONSTRAINT "BORROWS_PK" PRIMARY KEY ("BOOK_ID", "MSSN", "ISSUE_DATE"),
	 CONSTRAINT "VOLUMES_FK" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "VOLUMES" ("BOOK_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "BORROW_MEMBER_FK" FOREIGN KEY ("MSSN")
	  REFERENCES "MEMBER" ("SSN") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "ISSUE_MEMBER_FK" FOREIGN KEY ("ISSUED_BY")
	  REFERENCES "MEMBER" ("SSN") ON DELETE CASCADE ENABLE
   ) ;